### PR TITLE
Db setup

### PR DESCRIPTION
**Pull request by NolanCrenshaw**

### CODE REVIEW

**Comment by NolanCrenshaw** [comment]
I started this morning trying to merge all our initial work into the master branch.  
This is our initial setup, and things are pretty simple to just jam into the master. 
The branches Casey and I built merged no problem.
I hoped I could just work through some small differences between our models.py file. 
But this pull request is problematic. 
The issue is that Warren has removed the useless group-project-starter directory.
Now all our files are shifted up one directory.
This had to happen. It's the correct move. 
But I'm having serious difficulties merging the change.

**Comment by NolanCrenshaw** [comment]
Okay.
So git doesn't like to move files wholesale.
It was giving 'permission denied' when moving nested directories.
That was the bulk of the real problems. 
I went ahead and manually fixed the master branch.
We can go through the current pull conflicts together.

**Comment by DaedalusG** [comment]
F U

**Comment by DaedalusG** [comment]
JK no FU

**Pull request merged**
